package com.excilys.persistence;

import java.sql.*;
import java.util.ArrayList;

import static com.excilys.persistence.DAOUtility.*;

import com.excilys.mapper.ComputerMapper;
import com.excilys.model.Computer;

public class ComputerDAOImpl implements ComputerDAO {
	private DAOFactory daoFactory;
	private ComputerMapper computerMapper;
	
	private static final String SQL_SELECT_BY_ID = "SELECT id, name, introduced, discontinued, company_id FROM computer WHERE id = ?;";
	private static final String SQL_SELECT_ALL = "SELECT id, name, introduced, discontinued, company_id FROM computer;";
	private static final String SQL_INSERT = "INSERT INTO computer (name, introduced, discontinued, company_id) VALUES (?, ?, ?, ?)";
	private static final String SQL_DELETE = "DELETE FROM computer WHERE id = ?;";
	private static final String SQL_UPDATE = "UPDATE computer SET name = ?, introduced = ?, discontinued = ?, company_id = ? WHERE id = ?;";
	
	ComputerDAOImpl( DAOFactory daoFactory ) {
		this.daoFactory = daoFactory;
		this.computerMapper = new ComputerMapper();
	}

	@Override
	public ArrayList<Computer> list() throws DAOException {
	    ResultSet resultSet = null;
	    ArrayList<Computer> computers = new ArrayList<Computer>();
	    
	    try (
    		Connection connection = daoFactory.getConnection();
    		PreparedStatement preparedStatement = preparedStatementInitialization( connection, SQL_SELECT_ALL, false )
	    	) {
	    	
	        resultSet = preparedStatement.executeQuery();
	        
	        while ( resultSet.next() ) {
	        	computers.add( this.computerMapper.map( resultSet ) );
	        }
	        
	    } catch ( SQLException e ) {
			throw new DAOException( e );
		}
	    
		return computers;
	}

	@Override
	public Computer find(int pId) throws DAOException {
	    ResultSet resultSet = null;
	    Computer computer = null;
	    
	    try (
    		Connection connection = daoFactory.getConnection();
    		PreparedStatement preparedStatement = preparedStatementInitialization( connection, SQL_SELECT_BY_ID, false, pId )
	    	) {
	    	
	        resultSet = preparedStatement.executeQuery();
	        
	        if ( resultSet.next() ) {
	        	computer = this.computerMapper.map( resultSet );
	        } else {
	        	throw new DAOException("No SQL result for this computer ID.");
	        }
	        
	    } catch ( SQLException e ) {
			throw new DAOException( e );
		}
	    
		return computer;
	} 

	@Override
	public void create(Computer computer) throws DAOException {
	    ResultSet autoGeneratedValues = null;
	    
	    this.checkData( computer );

	    try (
	    	Connection connection = daoFactory.getConnection();
	    	PreparedStatement preparedStatement = preparedStatementInitialization( connection, SQL_INSERT, true, computer.getName(), computer.getIntroduced(), computer.getDiscontinued(), this.getCompanyId( computer ) )
	    	) {
	        
	        int statut = preparedStatement.executeUpdate();

	        if ( statut == 0 ) {
	            throw new DAOException( "Failed to create the computer in database, no line added in the table." );
	        }

	        autoGeneratedValues = preparedStatement.getGeneratedKeys();

	        if ( autoGeneratedValues.next() ) {
	        	computer.setId( autoGeneratedValues.getInt( 1 ) );
	        } else {
	            throw new DAOException( "Failed to create the computer in database, no auto-generated ID returned." );
	        }
	        
	    } catch ( SQLException e ) {
	        throw new DAOException( e );
	    }
	}

	@Override
	public void update(Computer computer) throws DAOException {
	    this.checkData( computer );

	    try (
	    	Connection connection = daoFactory.getConnection();
	    	PreparedStatement preparedStatement = preparedStatementInitialization( connection, SQL_UPDATE, false, computer.getName(), computer.getIntroduced(), computer.getDiscontinued(), this.getCompanyId( computer ), computer.getId() )
	    	) {

	        int statut = preparedStatement.executeUpdate();

	        if ( statut == 0 ) {
	            throw new DAOException( "Failed to delete the computer in database, no line deleted in the table." );
	        }

	    } catch ( SQLException e ) {
	        throw new DAOException( e );
	    }
	}

	@Override
	public void delete(Computer computer) throws DAOException {
	    try (
    		Connection connection = daoFactory.getConnection();
    		PreparedStatement preparedStatement = preparedStatementInitialization( connection, SQL_DELETE, false, computer.getId() )
	    	) {
	    	
	        int statut = preparedStatement.executeUpdate();

	        if ( statut == 0 ) {
	            throw new DAOException( "Failed to update the computer in database, no line updated in the table." );
	        }

	    } catch ( SQLException e ) {
	        throw new DAOException( e );
	    }
	}
	
	public void checkData(Computer computer) {
		if( computer.getName() == null ) {
	    	throw new DAOException("Failed to create computer : Computer name is null.");
	    }
	    
	    if( computer.getIntroduced() == null && computer.getDiscontinued() != null) {
	    	throw new DAOException("Failed to create computer : Dicontinued not null whereas introcued is.");
	    }
	    
	    if( ( computer.getIntroduced() != null && computer.getDiscontinued() != null ) && !computer.getDiscontinued().after(computer.getIntroduced() ) ) {
	    	throw new DAOException("Failed to create computer : Discontinuation date is not after the introduction date.");
	    }
	}
	
	public Integer getCompanyId( Computer computer ) {
		Integer companyID = null;
    	if(computer.getCompany() != null) {
    		companyID = computer.getCompany().getId();
    	}
    	return companyID;
	}

}
