package com.excilys.persistence;

import java.sql.*;
import java.util.ArrayList;

import static com.excilys.persistence.DAOUtility.*;

import com.excilys.model.Computer;

public class ComputerDAOImpl implements ComputerDAO {
	private DAOFactory daoFactory;
	
	private static final String SQL_SELECT_BY_ID = "SELECT id, name, introduced, discontinued, company_id FROM computer WHERE id = ?;";
	private static final String SQL_SELECT_ALL = "SELECT id, name, introduced, discontinued, company_id FROM computer;";
	private static final String SQL_INSERT = "INSERT INTO computer (name, introduced, discontinued, company_id) VALUES (?, ?, ?, ?)";
	private static final String SQL_DELETE = "DELETE FROM computer WHERE id = ?;";
	private static final String SQL_UPDATE = "UPDATE computer SET name = ?, introduced = ?, discontinued = ?, company_id = ? WHERE id = ?;";
	
	ComputerDAOImpl( DAOFactory daoFactory ) {
		this.daoFactory = daoFactory;
	}
	
	private static Computer map( ResultSet resultSet ) throws SQLException {
	    Computer computer = new Computer();
	    DAOFactory daoFactory = DAOFactory.getInstance();
	    CompanyDAO companyDAO = daoFactory.getCompanyDao();
	    
	    computer.setId( resultSet.getInt( "id" ) );
	    computer.setName( resultSet.getString( "name" ) );
	    computer.setIntroduced( resultSet.getTimestamp( "introduced" ) );
	    computer.setDiscontinued( resultSet.getTimestamp( "discontinued" ) );
	    computer.setCompany( companyDAO.find( resultSet.getInt( "company_id" ) ) );
	    
	    return computer;
	}

	@Override
	public ArrayList<Computer> list() throws DAOException {
		Connection connection = null;
	    PreparedStatement preparedStatement = null;
	    ResultSet resultSet = null;
	    ArrayList<Computer> computers = new ArrayList<Computer>();
	    
	    try {
	    	connection = daoFactory.getConnection();
	        preparedStatement = preparedStatementInitialization( connection, SQL_SELECT_ALL, false );
	        resultSet = preparedStatement.executeQuery();
	        
	        while ( resultSet.next() ) {
	        	computers.add( map( resultSet ) );
	        }
	    } catch ( SQLException e ) {
			throw new DAOException( e );
		} finally {
			closures( resultSet, preparedStatement, connection );
	    }
	    
		return computers;
	}

	@Override
	public Computer find(int pId) throws DAOException {
		Connection connection = null;
	    PreparedStatement preparedStatement = null;
	    ResultSet resultSet = null;
	    Computer computer = null;
	    
	    try {
	    	connection = daoFactory.getConnection();
	        preparedStatement = preparedStatementInitialization( connection, SQL_SELECT_BY_ID, false, pId );
	        resultSet = preparedStatement.executeQuery();
	        
	        if ( resultSet.next() ) {
	        	computer = map( resultSet );
	        }
	    } catch ( SQLException e ) {
			throw new DAOException( e );
		} finally {
			closures( resultSet, preparedStatement, connection );
	    }
	    
		return computer;
	} 

	@Override
	public void create(Computer computer) throws DAOException {
		Connection connection = null;
	    PreparedStatement preparedStatement = null;
	    ResultSet autoGeneratedValues = null;

	    try {
	    	connection = daoFactory.getConnection();
	    	
	    	Integer company_id = null;
	    	if(computer.getCompany() != null) {
	    		company_id = computer.getCompany().getId();
	    	}
	    	
	        preparedStatement = preparedStatementInitialization( connection, SQL_INSERT, true, computer.getName(), computer.getIntroduced(), computer.getDiscontinued(), company_id );
	        int statut = preparedStatement.executeUpdate();

	        if ( statut == 0 ) {
	            throw new DAOException( "Failed to create the computer in database, no line added in the table." );
	        }

	        autoGeneratedValues = preparedStatement.getGeneratedKeys();

	        if ( autoGeneratedValues.next() ) {
	        	computer.setId( autoGeneratedValues.getInt( 1 ) );
	        } else {
	            throw new DAOException( "Failed to create the computer in database, no auto-generated ID returned." );
	        }
	    } catch ( SQLException e ) {
	        throw new DAOException( e );
	    } finally {
	        closures( autoGeneratedValues, preparedStatement, connection );
	    }
	}

	@Override
	public void update(Computer computer) throws DAOException {
		Connection connection = null;
	    PreparedStatement preparedStatement = null;

	    try {
	    	connection = daoFactory.getConnection();
	        preparedStatement = preparedStatementInitialization( connection, SQL_UPDATE, false, computer.getName(), computer.getIntroduced(), computer.getDiscontinued(), computer.getCompany().getId(), computer.getId() );
	        int statut = preparedStatement.executeUpdate();

	        if ( statut == 0 ) {
	            throw new DAOException( "Failed to delete the computer in database, no line deleted in the table." );
	        }

	    } catch ( SQLException e ) {
	        throw new DAOException( e );
	    } finally {
	        closures( preparedStatement, connection );
	    }
	}

	@Override
	public void delete(Computer computer) throws DAOException {
		Connection connection = null;
	    PreparedStatement preparedStatement = null;

	    try {
	    	connection = daoFactory.getConnection();
	        preparedStatement = preparedStatementInitialization( connection, SQL_DELETE, false, computer.getId() );
	        int statut = preparedStatement.executeUpdate();

	        if ( statut == 0 ) {
	            throw new DAOException( "Failed to update the computer in database, no line updated in the table." );
	        }

	    } catch ( SQLException e ) {
	        throw new DAOException( e );
	    } finally {
	        closures( preparedStatement, connection );
	    }
	}

}
