package com.excilys.cdb.persistence;

import static com.excilys.cdb.persistence.DaoUtility.preparedStatementInitialization;

import com.excilys.cdb.exception.ComputerNullNameException;
import com.excilys.cdb.exception.DaoException;
import com.excilys.cdb.exception.DiscontinuedBeforeIntroducedException;
import com.excilys.cdb.exception.DiscontinuedButNoIntroducedException;
import com.excilys.cdb.mapper.ComputerDaoMapper;
import com.excilys.cdb.model.Computer;

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.Optional;

import org.apache.log4j.Logger;

public class ComputerDao {
  static final Logger LOGGER = Logger.getLogger(ComputerDao.class);
  private DaoFactory daoFactory;
  private ComputerDaoMapper computerMapper;

  private static final String SQL_SELECT_BY_ID = 
      "SELECT id, name, introduced, discontinued, company_id FROM computer WHERE id = ?";
  private static final String SQL_SELECT_ALL = 
      "SELECT id, name, introduced, discontinued, company_id FROM computer";
  private static final String SQL_INSERT = 
      "INSERT INTO computer (name, introduced, discontinued, company_id) VALUES (?, ?, ?, ?)";
  private static final String SQL_DELETE = 
      "DELETE FROM computer WHERE id = ?";
  private static final String SQL_UPDATE = 
      "UPDATE computer SET name = ?, introduced = ?, discontinued = ?, company_id = ? WHERE id = ?";
  private static final String SQL_SEARCH = 
	  "SELECT cpt.id, cpt.name, cpt.introduced, cpt.discontinued, cpt.company_id FROM computer cpt LEFT OUTER JOIN company cpn ON cpt.company_id=cpn.id WHERE cpt.name LIKE ? OR cpn.name LIKE ?";

  ComputerDao(DaoFactory daoFactory) {
    this.daoFactory = daoFactory;
    this.computerMapper = new ComputerDaoMapper();
  }

  public ArrayList<Computer> list() throws DaoException {
    LOGGER.info("Start computers listing...");
    ResultSet resultSet = null;
    ArrayList<Computer> computers = new ArrayList<Computer>();
 
    try (
        Connection connection = daoFactory.getConnection();
        PreparedStatement preparedStatement = preparedStatementInitialization(connection, SQL_SELECT_ALL, false)
    ) {
      resultSet = preparedStatement.executeQuery();
      
      while (resultSet.next()) {
        computers.add(this.computerMapper.map(resultSet));
      }
      
      connection.commit();
    } catch (SQLException e) {
      throw new DaoException(e);
    }

    if (computers.isEmpty()) {
      LOGGER.warn("Computers list is empty.");
    } else {
      LOGGER.info("Computers list created.");
    }

    return computers;
  }

  public Optional<Computer> findById(int pid) throws DaoException {
    ResultSet resultSet = null;
    Optional<Computer> computer = Optional.empty();

    try (
        Connection connection = daoFactory.getConnection();
        PreparedStatement preparedStatement = preparedStatementInitialization(connection, SQL_SELECT_BY_ID, false, pid)
    ) {
      resultSet = preparedStatement.executeQuery();

      if (resultSet.next()) {
        computer = Optional.ofNullable(this.computerMapper.map(resultSet));
      }
      
      connection.commit();
    } catch (SQLException e) {
      throw new DaoException(e);
    }
    
    if(computer.isPresent()) {
    	LOGGER.info("Computer " + pid + " found.");
    } else {
    	LOGGER.warn("Computer " + pid + " not found.");
    }
    
    return computer;
  }

  public void create(Computer computer) throws DaoException, ComputerNullNameException, DiscontinuedButNoIntroducedException, DiscontinuedBeforeIntroducedException {
    LOGGER.info("Start computer insertion...");
    ResultSet autoGeneratedValues = null;

    try (
        Connection connection = daoFactory.getConnection();
        PreparedStatement preparedStatement = 
              preparedStatementInitialization(connection, SQL_INSERT, true, 
                 computer.getName(), computer.getIntroduced().orElse(null),
                 computer.getDiscontinued().orElse(null), computer.getCompany().map(someCompany -> someCompany.getId()).orElse(null))
    ) {

      int statut = preparedStatement.executeUpdate();

      if (statut == 0) {
        throw new DaoException("Failed to create the computer in database, no line added in the table.");
      }

      autoGeneratedValues = preparedStatement.getGeneratedKeys();

      if (autoGeneratedValues.next()) {
        computer.setId(autoGeneratedValues.getInt(1));
      } else {
        throw new DaoException("Failed to create the computer in database, no auto-generated ID returned.");
      }
      
      connection.commit();
    } catch (SQLException e) {
      throw new DaoException("SQL error during creation.", e);
    }

    LOGGER.info("Computer " + computer.getId() + " created.");
  }

  public void update(Computer computerUpdated) throws DaoException, ComputerNullNameException, DiscontinuedButNoIntroducedException, DiscontinuedBeforeIntroducedException {
    LOGGER.info("Start computer " + computerUpdated.getId() + " update...");

    try (
         Connection connection = daoFactory.getConnection();
         PreparedStatement preparedStatement = 
             preparedStatementInitialization(connection, SQL_UPDATE, false,
             computerUpdated.getName(), computerUpdated.getIntroduced().orElse(null),
             computerUpdated.getDiscontinued().orElse(null), computerUpdated.getCompany().map(someCompany -> someCompany.getId()).orElse(null), computerUpdated.getId())
    ) {
      int statut = preparedStatement.executeUpdate();

      if (statut == 0) {
        throw new DaoException("Failed to update the computer in database, no line updated in the table.");
      }
      
      connection.commit();
    } catch (SQLException e) {
      throw new DaoException("SQL error during update.", e);
    }

    LOGGER.info("Computer " + computerUpdated.getId() + " updated.");
  }

  public void delete(Computer computer) throws DaoException {
    try (
         Connection connection = daoFactory.getConnection();
         PreparedStatement preparedStatement = preparedStatementInitialization(connection, SQL_DELETE, false, computer.getId())
    ) {
      int statut = preparedStatement.executeUpdate();
      if (statut == 0) {
        throw new DaoException("Failed to delete the computer in database, no line deleted in the table.");
      }
      
      connection.commit();
    } catch (SQLException e) {
      throw new DaoException("SQL error during deletion.", e);
    }

    LOGGER.info("Computer " + computer.getId() + " deleted.");
  }
  
  public ArrayList<Computer> search(String search) throws DaoException {
	LOGGER.info("Start research for '" + search + "'...");
    ResultSet resultSet = null;
    ArrayList<Computer> computers = new ArrayList<Computer>();
 
    try (
        Connection connection = daoFactory.getConnection();
        PreparedStatement preparedStatement = preparedStatementInitialization(connection, SQL_SEARCH, false, "%" + search + "%", "%" + search + "%")
    ) {
      resultSet = preparedStatement.executeQuery();
      
      while (resultSet.next()) {
        computers.add(this.computerMapper.map(resultSet));
      }
      
      connection.commit();
    } catch (SQLException e) {
      throw new DaoException(e);
    }

    if (computers.isEmpty()) {
      LOGGER.warn("No computer found for '" + search + "' search.");
    } else {
      LOGGER.info(computers.size() + " computer(s) found.");
    }

    return computers;
  }

  public Integer getCompanyId(Computer computer) {
	return computer.getCompany().map(someCompany -> someCompany.getId()).orElse(null);
  }
}
